---
###############################################################################
# Deluge Role Options
###############################################################################
# Use Debian package for installation.
#
# Updates:
# * Branch for new Debian releases.
# * KEEP a separate change log as changes are made.
# * Use Debian docs to validate package/process changes.
#   * Reference source docs if needed.
# * Update role defaults (includes updating defaults, tasks):
#   * Use configuration docs to add new variables.
#   * Use defaults to remove any changed/deprecated variables.
# * Update tests for any changes.
# * Standard role validation testing (yamllint, ansible-lint, to-do, no-qa).
# * Tag with OS-APP-ROLE version.
#
# Reference:
# * https://delugecom.github.io/#debian-repository
# * https://deluge.com

# Last time Deluge options were validated against a default configuration.
deluge_role_validate_date: '2025-08-24'
deluge_role_validate_release: 'trixie'
deluge_role_validate_version: '2.2.0'

###############################################################################
# APT Packages
###############################################################################

deluge_role_packages:
  - 'deluged'  # Daemon (required).
  - 'deluge-console'  # CLI interface (required).
  - 'deluge-web'  # WebUI (required).
  - 'rsync'  # ansible.builtin.synchronize.
  - 'unrar'  # Requires: contrib, non-free.
  - 'unzip'  # Provides: zip.
  - '7zip'  # Provides: 7zz.
  - 'p7zip-full'  # Provides: 7za.

# Debian APT sources to use if package install fails.
deluge_role_apt_debian_all:
  - name: 'debian'
    types:
      - 'deb'
      - 'deb-src'
    uris: 'http://deb.debian.org/debian'
    suites:
      - 'trixie'
      - 'trixie-updates'
      - 'trixie-backports'
    components:
      - 'main'
      - 'contrib'
      - 'non-free'
      - 'non-free-firmware'
    signed_by: '/usr/share/keyrings/debian-archive-keyring.gpg'
  - name: 'debian-security'
    types:
      - 'deb'
      - 'deb-src'
    uris: 'http://deb.debian.org/debian-security'
    suites:
      - 'trixie-security'
    components:
      - 'main'
      - 'contrib'
      - 'non-free'
      - 'non-free-firmware'
    signed_by: '/usr/share/keyrings/debian-archive-keyring.gpg'

###############################################################################
# Default Deluge User/Group
###############################################################################

deluge_role_group:
  name: 'media'
  gid: 5555

deluge_role_user:
  name: 'media'
  group: 'media'
  uid: 5555
  shell: '/usr/sbin/nologin'
  home: '/nonexistent'
  create_home: false
  password: '!'
  password_lock: true
  update_password: 'always'
  expires: -1
  system: true
