---
###############################################################################
# Deluge Role Options
###############################################################################
#
# Updates:
# * New MAJOR, MINOR releases should hard branch at version before starting
#   (e.g. 3.0.x branch).
# * Debian OS version is irrelevant (tied to APT package version).
# * Keep a separate change log as changes are made, you will not remember all
#   of them.
# * Use debian docs to validate package/process changes. Reference source docs
#   if needed.
# * Update role defaults (includes updating defaults, tasks):
#   * Use configuration docs to add new variables.
#   * Use defaults/ to remove any changed/deprecated variables.
# * Update tests for any changes.
# * Standard role validation testing (yamllint, ansible-lint, todo, noqa).
# * Tag with MAJOR.MINOR.PATCH[ROLE] version, with PATCH representing role
#   change - e.g. Debian: 2.0.3 -> Role: 2.0.301  (01 role release).
#
# Reference:
# * https://delugecom.github.io/#debian-repository
# * https://deluge.com

# Last time Deluge options were validated against a default configuration.
deluge_role_validate_date: '2025-02-08'
deluge_role_validate_release: 'bookworm'
deluge_role_validate_version: '2.0.3'

###############################################################################
# APT Packages
###############################################################################

deluge_role_packages:
  - 'deluged'  # daemon (required).
  - 'deluge-console'  # CLI interface (required).
  - 'deluge-web'  # WebUI (required).
  - 'rsync'  # ansible.builtin.synchronize.
  - 'unrar'  # requires: contrib, non-free.
  - 'unzip'
  - '7zip'  # provides: 7zz.
  - 'p7zip-full'  # provides: 7za.

# Debian APT sources to use if package install fails.
deluge_role_apt_debian_all:
  - name: 'debian'
    types:
      - 'deb'
      - 'deb-src'
    uris: 'http://deb.debian.org/debian'
    suites:
      - 'bookworm'
      - 'bookworm-updates'
      - 'bookworm-backports'
    components:
      - 'main'
      - 'contrib'
      - 'non-free'
      - 'non-free-firmware'
    signed_by: '/usr/share/keyrings/debian-archive-keyring.gpg'
  - name: 'debian-security'
    types:
      - 'deb'
      - 'deb-src'
    uris: 'http://deb.debian.org/debian-security'
    suites:
      - 'bookworm-security'
    components:
      - 'main'
      - 'contrib'
      - 'non-free'
      - 'non-free-firmware'
    signed_by: '/usr/share/keyrings/debian-archive-keyring.gpg'

###############################################################################
# Default Deluge User/Group
###############################################################################

deluge_role_group:
  name: 'media'
  gid: 5555

deluge_role_user:
  name: 'media'
  group: 'media'
  uid: 5555
  shell: '/usr/sbin/nologin'
  home: '/nonexistent'
  create_home: false
  password: '!'
  password_lock: true
  update_password: 'always'
  expires: -1
  system: true
