---
###############################################################################
# Configure Deluge Install
###############################################################################
# Run Deluge under specific role user, using systemd logging instead of log
# files; add ability to restart the service daily.
#
# Do not remove the default (debian-deluged) user as this will put APT in a
# broken state. Instead ensure the account is fully locked.
#
# NOTE
# > Deluge will silently fail parsing configuration files and continue
# > starting - leading to a partially configured state. Errors in rendering
# > config files may be expressed as 'working' but not all set options
# > configured or work; these will all occur after the parsing error. This
# > applies to ALL parsed configs.
# >
# > Debugging requires working backwards in the config until the errors are
# > found.
#
# New Deluge options must be manually added to the template and role
# default templates.
#
# Args:
#   _deluge_cfg_map: list of dict - Annotated config map.
#   _deluge_cfg_order: list of str - Config section order.
#
# Reference:
# * https://delugecom.github.io/#debian-repository
# * https://deluge.com

- name: 'Config | lock Deluge package user'
  when: deluge_srv_user.raw != 'debian-deluged'
  ansible.builtin.user:
    name: 'debian-deluged'
    password: '!'
    password_lock: true

# Permissions determined from vanilla service start
- name: 'Config | manage config directories'
  ansible.builtin.file:
    path: '{{ deluge_srv_config_dir.parsed ~ item.path }}'
    owner: '{{ deluge_srv_user.parsed }}'
    group: '{{ deluge_srv_user.parsed }}'
    mode: '{{ item.mode }}'
    recurse: true
    state: 'directory'
  become: true
  changed_when: false  # https://github.com/ansible/ansible/issues/32636
  loop:
    - path: 'icons'
      mode: '0750'
    - path: 'plugins'
      mode: '0770'
    - path: 'ssl'
      mode: '0770'
    - path: 'state'
      mode: '0770'
    - path: 'scripts'
      mode: '0770'
  loop_control:
    label: '{{ item.path }}'

- name: 'Config | manage media directories'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ deluge_srv_user.parsed }}'
    group: '{{ deluge_srv_group.parsed }}'
    mode: '{{ deluge_srv_media_perms_folder.raw }}'
    state: 'directory'
  become:
    '{{ true if deluge_srv_user_data_manage_enable.raw else omit }}'
  become_user: '{{
      deluge_srv_user.raw
      if deluge_srv_user_data_manage_enable.raw else
      omit
    }}'
  loop:
    - '{{ deluge_cfg_core_download_location.raw }}'
    - '{{ deluge_cfg_core_move_completed_path.raw }}'
    - '{{ deluge_cfg_core_torrentfiles_location.raw }}'

- name: 'Config | set media file permissions'
  when: deluge_srv_media_set_perms_file_enable.raw
  ansible.builtin.shell: >-
    find '{{ item }}'
    -type f
    -exec chmod {{ deluge_srv_media_perms_file.raw }} {};
      chown {{ deluge_srv_user.parsed }}:{{ deluge_srv_group.parsed }} {} \;
  changed_when: false
  become:
    '{{ true if deluge_srv_user_data_manage_enable.raw else omit }}'
  become_user: '{{
      deluge_srv_user.raw
      if deluge_srv_user_data_manage_enable.raw else
      omit
    }}'
  loop:
    - '{{ deluge_cfg_core_download_location.raw }}'
    - '{{ deluge_cfg_core_move_completed_path.raw }}'
    - '{{ deluge_cfg_core_torrentfiles_location.raw }}'

- name: 'Config | set daemon HTTPS certs'
  when: deluge_cfg_web_https.raw
  ansible.builtin.copy:
    src: '{{ item.parsed }}'
    dest: '{{ item.raw }}'
    owner: '{{ deluge_srv_user.parsed }}'
    group: '{{ deluge_srv_group.parsed }}'
    mode: '0600'
    force: true
  loop:
    - '{{ deluge_cfg_web_ssl_cert_path }}'
    - '{{ deluge_cfg_web_ssl_key_path }}'
  loop_control:
    label: '{{ item.raw }}'

# Deluged will always re-create default daemon.* on startup; remove custom.
- name: 'Config | remove daemon HTTPS certs'
  when: not deluge_cfg_web_https.raw
  ansible.builtin.file:
    dest: '{{ item }}'
    state: 'absent'
  loop:
    - '{{ deluge_cfg_web_ssl_cert_path.parsed }}'
    - '{{ deluge_cfg_web_ssl_key_path.parsed }}'
  loop_control:
    label: '{{ item }}'

- name: 'Config | set core.conf'
  ansible.builtin.template:
    src: 'core.conf.j2'
    dest: '{{ deluge_srv_config_dir.parsed ~ "core.conf" }}'
    owner: '{{ deluge_srv_user.parsed }}'
    group: '{{ deluge_srv_group.parsed }}'
    mode: '0600'

- name: 'Config | set web.conf'
  ansible.builtin.template:
    src: 'web.conf.j2'
    dest: '{{ deluge_srv_config_dir.parsed ~ "web.conf" }}'
    owner: '{{ deluge_srv_user.parsed }}'
    group: '{{ deluge_srv_group.parsed }}'
    mode: '0600'

- name: 'Config | configure plugins'
  ansible.builtin.include_tasks: 'plugins.yml'

- name: 'Config | set service drop-ins'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.systemd'
  vars:
    systemd_daemon_reload_enable: true
    systemd_services:
      - name: 'deluged'
        state: 'present'
        drop_in: true
        service:
          exec_start:
            - ''
            - >-
              /usr/bin/deluged -d
              --loglevel {{ deluge_srv_log_level.raw }}
              --config "{{ deluge_srv_config_dir.parsed }}"
          restart: 'always'  # Always restart for periodic service restarts.
          runtime_max_sec:
            '{{ "1d" if deluge_srv_restart_daily_enable.raw else "infinity" }}'
        exec:
          user: '{{ deluge_srv_user.raw }}'
          group: '{{ deluge_srv_group.raw }}'
      - name: 'deluge-web'
        state: 'present'
        drop_in: true
        service:
          exec_start:
            - ''
            - >-
              /usr/bin/deluge-web -d
              --loglevel {{ deluge_srv_log_level.raw }}
              --config "{{ deluge_srv_config_dir.parsed }}"
          restart: 'always'  # Always restart for periodic service restarts.
          runtime_max_sec:
            '{{ "1d" if deluge_srv_restart_daily_enable.raw else "infinity" }}'
        exec:
          user: '{{ deluge_srv_user.raw }}'
          group: '{{ deluge_srv_group.raw }}'

- name: 'Config | start Deluge'
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: 'restarted'
  loop:
    - 'deluged.service'
    - 'deluge-web.service'
