---
# yamllint disable rule:line-length
###############################################################################
# Install Deluge Packages
###############################################################################
# Use custom service according to Linux FHS standards:
#
# Type    | Perms               | Path
# --------|---------------------|-------
# Runtime | 0750/0640 SRV:SRV   | /var/opt/deluge
# Config  | 0640 SRV:SRV        | /etc/opt/deluge
#
# Installation notes:
# * Package does not follow Debian standards (defaults, DEBCONF options).
#     Resolution: Use overrides.conf only.
# * Deluge requires APT Debian components contrib, non-free to be enabled for
#   all dependencies to be installed.
#     Resolution: Flag for explicitly disabling sources.
# * Removing deluge user breaks APT package.
#     Resolution: Lock deluge user and prevent use with role.
# * Install places services in /var/lib/deluged owned by deluge. Changing the
#   user/group for this location breaks package upgrades.
#     Resolution: Create FHS standard locations and use service drop-ins.
#
# Reference:
# * https://deluge.readthedocs.io/en/latest/how-to/systemd-service.html
# * https://archlinuxarm.org/forum/viewtopic.php?f=30&t=7729
# * https://linuxconfig.org/set-up-a-headless-deluge-server-on-linux
# * https://serverfault.com/questions/22414/how-can-i-run-debian-stable-but-install-some-packages-from-testing
# yamllint enable rule:line-length

- name: 'Install | filesystem | set system directories'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ deluge__srv._user }}'
    group: '{{ deluge__srv._group }}'
    mode: '0755'
    state: 'directory'
  loop:
    - '{{ deluge___app._etc_d }}'
    - '{{ deluge___app._cfg_d }}'  # cfg_dir includes var_dir.

- name: 'Install | packages'
  when: deluge_flg_apt_sources
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ deluge___packages }}'
    apt_sources:
      '{{ deluge___apt_debian_all if deluge_flg_apt_sources else [] }}'
    apt_srv_sources_list_disable: true
    apt_srv_package_update_cache: true

- name: 'Install | stop services'
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: 'stopped'
  failed_when: false
  loop:
    - 'deluged.service'
    - 'deluge-web.service'

- name: 'Install | account | lock debian-deluged'
  when: deluge__srv._user != 'debian-deluged'
  ansible.builtin.user:
    name: 'debian-deluged'
    password: '!'
    password_lock: true

- name: '{{ "Install | filesystem | set minimal " ~ deluge___app._core }}'
  when: deluge__cfg._d | length == 0
  ansible.builtin.template:
    src: 'templates/default/core.conf'
    dest: '{{ deluge___app._core }}'
    owner: '{{ deluge__srv._user }}'
    group: '{{ deluge__srv._group }}'
    mode: '0600'

- name: 'Install | filesystem | set /etc/systemd/system'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'
  loop:
    - '{{ deluge___app._srv_drop_in | dirname }}'
    - '{{ deluge___app._web_drop_in | dirname }}'

- name: '{{ "Install | filesystem | set " ~ deluge___app._srv_drop_in }}'
  ansible.builtin.template:
    src: 'systemd/deluged.override.conf.j2'
    dest: '{{ deluge___app._srv_drop_in }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: deluge__srv_override

- name: '{{ "Install | filesystem | set " ~ deluge___app._web_drop_in }}'
  ansible.builtin.template:
    src: 'systemd/deluge-web.override.conf.j2'
    dest: '{{ deluge___app._web_drop_in }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: deluge__web_override
