---
###############################################################################
# Pre Execution Tasks
###############################################################################
# Only use data annotations in role after merging role, defaults, runtime data.
# Service may not exist if first install.
#
# Reference:
# * https://deluge-torrent.org

- name: 'Prep | fact | record start time'
  ansible.builtin.set_fact:
    deluge__srv: "{{ deluge___release | r_pufky.data.v3(

        _start=now(utc=True, fmt='%Y-%m-%dT%H%M%S'),
        _log_level=deluge_srv_log_level,
        _user=deluge_srv_user,
        _group=deluge_srv_group,
      ) }}"
    deluge__cfg: "{{ {} | r_pufky.data.v3(

        _d=deluge_cfg_d | regex_replace('\\/$', ''),
      ) }}"

- name: 'Prep | assert | service user is not deluge'
  ansible.builtin.assert:
    quiet: true
    that:
      - deluge__srv._user != 'deluge'
      - deluge__srv._group != 'deluge'
    fail_msg: |

      ✘ deluge service user/group must NOT be 'deluge'.
      Create a custom user before executing this role or use 'media' to
      automatically create a service user for deluge.

      deluge_srv_user: {{ deluge__srv._user }}
      deluge_srv_group: {{ deluge__srv._group }}

- name: 'Prep | assert | config enabled and source defined'
  when: deluge_flg_config
  ansible.builtin.assert:
    quiet: true
    that:
      - deluge__cfg._d | length > 0
    fail_msg: |

      ✘ Config source not set.
      Config source enabled but no config source defined.

      deluge_flg_config: {{ deluge_flg_config }}
      deluge_cfg_d: {{ deluge__cfg._d }}

- name: '{{ "Prep | account | query user " ~ deluge__srv._user }}'
  ansible.builtin.command: '{{ "id " ~ deluge__srv._user }}'
  failed_when: false
  register: deluge__cfg_check
  changed_when: deluge__cfg_check.rc > 0

- name: '{{ "Prep | account | query group " ~ deluge__srv._group }}'
  ansible.builtin.command: '{{ "groups " ~ deluge__srv._group }}'
  failed_when: false
  register: deluge__group_check
  changed_when: deluge__group_check.rc > 0

- name: '{{ "Prep | account | create group " ~ deluge__srv._group }}'
  when: deluge__group_check.rc != 0
  ansible.builtin.group:
    gid: '{{ deluge___group.gid }}'
    name: '{{ deluge___group.name }}'
    state: 'present'

- name: '{{ "Prep | account | create user " ~ deluge__srv._user }}'
  when: deluge__cfg_check.rc != 0
  ansible.builtin.user:
    name: '{{ deluge___user.name }}'
    group: '{{ deluge___user.group }}'
    uid: '{{ deluge___user.uid }}'
    shell: '{{ deluge___user.shell }}'
    home: '{{ deluge___user.home }}'
    create_home: '{{ deluge___user.create_home }}'
    password: '{{ deluge___user.password }}'
    password_lock: '{{ deluge___user.password_lock }}'
    update_password: '{{ deluge___user.update_password }}'
    expires: '{{ deluge___user.expires }}'
    system: '{{ deluge___user.system }}'

# Pre-existing users may have a different UID/GID/Home.
- name: '{{ "Prep | account | enumerate " ~ deluge__srv._user }}'
  ansible.builtin.user:
    name: '{{ deluge__srv._user }}'
  check_mode: true
  changed_when: false
  register: deluge__cfg_query

- name: 'Prep | fact | parse service UID/GID'
  ansible.builtin.set_fact:
    deluge__cfg: "{{ deluge__cfg | r_pufky.data.v3(

        _uid=deluge__cfg_query.uid,
        _gid=deluge__cfg_query.group,
      ) }}"

# Render configuration locally and resolve configured service paths.
- name: 'Prep | fact | resolve deluge.conf'
  ansible.builtin.set_fact:
    deluge__srv: "{{ deluge__srv | r_pufky.data.v3(

        _tmpl_cfg=lookup(
          'ansible.builtin.template',
          deluge__cfg._d ~ '/core.conf'
          if deluge__cfg._d | length > 0 else
          'templates/default/core.conf'
        ),
      ) }}"

- name: 'Prep | fact | parse directories'
  ansible.builtin.set_fact:
    deluge__srv: "{{ deluge__srv | r_pufky.data.v3(

        _cfg_download_location=(
          deluge__srv._tmpl_cfg |
          regex_search(
              '\"download_location\":\\s*\"(.*?)\"', '\\1', multiline=True
            ) |
          default([''], true) | first
        ),
        _cfg_move_completed_path=(
          deluge__srv._tmpl_cfg |
          regex_search(
              '\"move_completed_path\":\\s*\"(.*?)\"', '\\1', multiline=True
            ) |
          default([''], true) | first
        ),
        _cfg_plugins_location=(
          deluge__srv._tmpl_cfg |
          regex_search(
              '\"plugins_location\":\\s*\"(.*?)\"', '\\1', multiline=True
            ) |
          default([''], true) | first
        ),
        _cfg_torrentfiles_location=(
          deluge__srv._tmpl_cfg |
          regex_search(
              '\"torrentfiles_location\":\\s*\"(.*?)\"', '\\1', multiline=True
            ) |
          default([''], true) | first
        ),
      ) }}"

- name: 'Prep | systemd | stop deluge.service'
  ansible.builtin.systemd:
    name: 'deluge.service'
    state: 'stopped'
  failed_when: false
