---
# yamllint disable rule:line-length
###############################################################################
# Deluge Prep
###############################################################################
# Deluge install from deb packages are categorically broken. There are no
# debconf options.
#
# Prepare system for install by creating user/group for service, add drop-in
# for user/group service override, and sanitize (standardize with default
# values if not set) Deluge configuration.
#
# Debian install places services in /var/{lib,log}/deluged owned by
# debian-deluged. Create /var/{lib,log}/deluge with configured user and
# override services for those users and new location. Leave package locations
# untouched to ensure package upgrades work properly.
#
# Do not remove the default (debian-deluged) user as this will put APT in a
# broken state. Instead ensure the account is fully locked.
#
# The default password is 'deluge' and is hardcoded if a password is not set
# in web.conf.
#
# For updates search the source code for undocumented variable usage and
# changes.
#
# Reference:
# * https://deluge-torrent.org/
# * https://deluge.readthedocs.io/en/latest/how-to/systemd-service.html
# * https://archlinuxarm.org/forum/viewtopic.php?f=30&t=7729
# * https://linuxconfig.org/set-up-a-headless-deluge-server-on-linux
# * https://serverfault.com/questions/22414/how-can-i-run-debian-stable-but-install-some-packages-from-testing
# yamllint enable rule:line-length

- name: 'Prep | assert SSL requirements'
  when: _deluge_cfg_web_https.raw
  ansible.builtin.assert:
    quiet: true
    that:
      - _deluge_cfg_web_ssl_cert_path.raw | length > 0
      - _deluge_cfg_web_ssl_key_path.raw | length > 0
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │                     SSL Requirements NOT met.                     │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ deluge_cfg_web_https=true requires:
      │ * deluge_cfg_web_ssl_cert_path set
      │ * deluge_cfg_web_ssl_key_path set

- name: 'Prep | manage users'
  when: _deluge_srv_create_user.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_user: '{{ deluge_role_user }}'
    users_role_group: '{{ deluge_role_group }}'

- name: 'Prep | enumerate system user {{ _deluge_srv_user.raw }}'
  ansible.builtin.user:
    name: '{{ _deluge_srv_user.raw }}'
  check_mode: true
  changed_when: false
  register: _deluge_srv_user_query

- name: 'Prep | parse system user UID/GID'
  ansible.builtin.set_fact:
    _deluge_srv_user: '{{
        _deluge_srv_user |
        combine({"_uid": _deluge_srv_user_query.uid})
      }}'
    _deluge_srv_group: '{{
        _deluge_srv_group |
        combine({"_gid": _deluge_srv_user_query.group})
      }}'
