---
###############################################################################
# HTTPS
###############################################################################
# HTTPS successful deployment with password.
#
# Tests:
# * deluged.service active and running.
# * deluge-web.service active and running.
# * /opt/deluge/config/ssl/daemon.* set.
# * HTTPS enabled, with password 'test'.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        deluge_cfg_web_https: true
        deluge_cfg_web_ssl_cert_path: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/test.pem"
          }}'
        deluge_cfg_web_ssl_key_path: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/test.key"
          }}'
        deluge_cfg_web_pwd_salt: 'e0156aa94ecff125dc48665acf3b6b5842588c11'
        deluge_cfg_web_pwd_sha1: '75559193c309f82bedbd5d865d45ac16a90db577'
platforms:
  - name: 'deluge-debian-13-https'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
