---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | /opt/deluge/config/ssl'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | /opt/deluge/config/ssl/{{ item.file }}'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/" ~ item.src
          }}'
        test_file: '/opt/deluge/config/ssl/{{ item.file }}'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'
      loop:
        - {src: 'test.pem', file: 'daemon.cert'}
        - {src: 'test.key', file: 'daemon.pkey'}
      loop_control:
        label: '{{ item.file }}'
