---
- name: 'Default | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | gather service status'
      ansible.builtin.service_facts:

    # Deluge will fail if configuration is bad.
    - name: 'Default | verify | assert deluged.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"deluged.service" in ansible_facts.services'
          - 'ansible_facts["services"]["deluged.service"]["state"] == "running"'  # yamllint disable-line rule:line-length
        fail_msg: '✘ deluged.service should be enabled and running.'

    - name: 'Default | verify | assert deluge-web.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"deluge-web.service" in ansible_facts.services'
          - 'ansible_facts["services"]["deluge-web.service"]["state"] == "running"'  # yamllint disable-line rule:line-length
        fail_msg: '✘ deluge-web.service should be enabled and running.'

    - name: 'Default | verify | /var/lib/deluge'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | /var/lib/deluge'
        test_file: '/var/lib/deluge'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0750'
        test_state: 'directory'
